#!/usr/bin/env bash

# Aliases
alias lg="ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//-/g' -e 's/^/ /' -e 's/-/|/'"
alias sites="cd ~/Sites"
alias top='top -ocpu'
alias tmux='tmux -2'
alias localenv='. env/bin/activate'
alias fixkb='setxkbmap -option ctrl:nocaps'

# t Aliases
alias t='python /usr/bin/t/t.py --task-dir ~/Dropbox/tasks --list tasks'
alias b='python /usr/bin/t/t.py --task-dir . --list bugs'
# alias to love
alias love="/Applications/love.app/Contents/MacOS/love"

alias tron='rlwrap sbcl --eval "(ql:quickload :shuffletron)" --eval "(shuffletron:run)"'

#function activate() {
#    source ~/source/jellydoughnut/three_venv.sh
#}
