#!/usr/bin/env bash

# Aliases
# alias ls="ls -lhFG"
alias ls="ls -aFGhkLlpsTP"
alias l="ls"
alias lg="ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//-/g' -e 's/^/ /' -e 's/-/|/'"
alias sites="cd ~/Sites"
alias medley="cd ~/devel/cms_dev/src/medley-templates"
alias storyville="cd ~/devel/cms_dev/src/storyville"
alias top='top -ocpu'
alias tmux='tmux -2'

# t Aliases
alias t='python /usr/bin/t/t.py --task-dir ~/Dropbox/tasks --list tasks'
alias b='python /usr/bin/t/t.py --task-dir . --list bugs'

# Start and Stop Servers
alias start_mysql="sudo launchctl load -w /Library/LaunchDaemons/com.mysql.mysqld.plist"
alias stop_mysql="sudo launchctl unload -w /Library/LaunchDaemons/com.mysql.mysqld.plist"
alias start_postgres="/usr/local/pgsql/bin/pg_ctl -D /usr/local/pgsql/data -l logfile start"
alias stop_postgres="/usr/local/pgsql/bin/pg_ctl -D /usr/local/pgsql/data -l logfile stop"
alias start_redis="redis-server /Users/kennethlove/Developer/etc/redis.conf"
alias start_mongo="mongod run --config /Users/kennethlove/Developer/Cellar/mongodb/1.6.5-x86_64/mongod.conf"

function activate() {
    source ~/source/jellydoughnut/three_venv.sh
}
